version: "3.9"
services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: callme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - callme

networks:
  callme: null
