version: "3.9"
services:

  eventsourcing-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: callme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - callme

volumes:
  esdata:
    driver: local

networks:
  callme: null
